export const DB = "testing";

export const AUTH_STATUS = {
  PENDING: 'PENDING',
  NOT_REGISTERED: 'NOT_REGISTERED',
  REGISTERED: 'REGISTERED',
  ADMIN_ACCESS: 'ADMIN_ACCESS',
  SUPER_ADMIN_ACCESS: 'SUPER_ADMIN_ACCESS',
  NMS_MEMBER:"NMS_MEMBER"
};